// <auto-generated />
using AjaxDefinex.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AjaxDefinex.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250313132643_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AjaxDefinex.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Elektronik"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mobilya"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Giyim"
                        });
                });

            modelBuilder.Entity("AjaxDefinex.Models.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Laptop",
                            Price = 12000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Telefon",
                            Price = 8000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Kulaklık",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Masa",
                            Price = 3000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Sandalye",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Koltuk",
                            Price = 5000m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Gömlek",
                            Price = 500m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Pantolon",
                            Price = 600m
                        });
                });

            modelBuilder.Entity("AjaxDefinex.Models.Entities.Product", b =>
                {
                    b.HasOne("AjaxDefinex.Models.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AjaxDefinex.Models.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
